name = "ClaudePrompting"
uuid = "8162bfbc-b172-4228-a17a-55f2feada2e8"
authors = ["Kwang-Seuk <kjeong@bhug.ac.kr> and contributors"]
version = "1.0.0-DEV"

[deps]
AES = "5a3fb44e-d90d-11e9-053b-99581e1bac63"
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
MbedTLS = "739be429-bea8-5141-9913-cc70e7f3736d"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PromptingTools = "670122d1-24a8-4d70-bfce-740807c42192"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
AES = "0.1"
CSV = "0.10"
DataFrames = "1"
HTTP = "1"
JSON3 = "1"
MbedTLS = "1"
OrderedCollections = "1"
PromptingTools = "0.57, 0.70"
SHA = "0.7"
YAML = "0.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
